language: python

cache: pip

python:
- '3.5'
- '3.6'
- nightly

matrix:
  allow_failures:
  - python: nightly

before_install:
- sudo apt-get update
- sudo apt-get install pandoc -y
- pip install pipenv codecov

install:
- pipenv install --dev

script:
- pipenv run make lint
- pipenv run make test

deploy:
  provider: pypi
  user: stegben
  password:
    secure: B3UVec1RygGoGG6XJv3Rhv8F/4RH2ZCiAQtsMA8KXrW7YDiAirD5vKQO1wTmMrL7/TeOJQwynQRb5wAE+tNU2K3yWATokll7ClgbSBXRRdSUO6E+K2Qo8CIfw8L55zygtXeg/AQIpCKte1v5kUAKJLKnKgkIouRcYEDuUYlhurcbxhYVJxBKKJvB6zzHueCHCFT19to3/QCMkJy9AIUL6taRe3P9AZVVBVllmS9pA74Hn3BQJcyHkAF5fH5MzUdXzMEY69/oZh5GDKCkT0Vpm/vLAc+f8hdPc9o/0jR/zKgMrkl83pkYdK9loMzUh9wb2kXSJV1Mc6q7RWHAQ4+9q5tVw5x5m71Xx+0SeR6Y+QVHascW+I15MHwXKnoIFRy1UqT9cWoffG5KYxTOwp/38G8aPq9MQbEEgaSxUjYH9PmrumniDYyNiw9+W8XroUtO25Q2VMvKyhrcKrWohR+ENpJVhV5X5xaioUT/tSdfNVzpcvdCty764AJpCJfw4XUEmJlTIuP/id5lhdhGktZU9wjO6Pf6PyyLP9o6fFIRFeFoPnxwgFwAPP3jk42x9keKb4S7Bzc4Kyc5J0s40HseW4gGx8QC8vRirJLAvfqHlNCWcU9Z7SEjjStGAd/lldTBr2WpZobfEzTK0jvDwHYVsy81DhEiIs8cIhK9r3JEqAA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: stegben/aiomessenger

after_success:
- codecov
