language: python

cache: pip

python:
- '3.5'
- '3.6'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

before_install:
  - sudo apt-get update
  - sudo apt-get install pandoc -y
  - pip install pipenv codecov

install:
- pipenv install --dev

script:
- pipenv run make lint
- pipenv run make test

deploy:
  provider: pypi
  user: stegben
  password:
    secure: "HAUYhGyTqXeXUKvht1mO99yTaw2IfOrmAzKECwgERZ25idhCPu4EmtaQYO/MSgIWDn2a3QF6Ws7jSm/yjS8dwbUBK975DOkgYLA+ETjV3ISbARn3nSt5b6QWf86zPurTSnw1Qe5rGmgUxSVEVzETA6k8ps7S5RiL2vkB58UO8XMgnUoJ65oOfZMyy54XJ4mq68ek1y7K4X+JE8UEyh/UIqB999FMUvhOFk/S9EJShk3ecafzNKA/i0I1Mslj8fauxFah6aZaPRBgKtrrt9+bOHT7ByxX4RW/DxvKCBqphvXb16PQfMO42y1TUW4IkhdoROEwMFuBJ1rqVvaO881V/8097jsK57wZKI7JV+ARsM2eRv82FfEn9N1MB5NB/ZOuWITb9z0m7mR6MCtEShpHBW5rdnRqkr2IRV9PEWZBoQxF8VZ2X3XrsgH3fr6/Qc8wPr0lx8J+TzjuOOSClTb5WeENry5kbRKzM9Rm3be5c1AGRCuXsIWkItlRK9ogLRgMUka70FKldln4S+XbwrqcjzxBPNgtTtjWAPGdUYYQjWG1FVpIp5FBgZ27XbVCo4bJ0l70GOenxJYHGwbzljXqwGHVOfj8k5pJPeSlN+3fdVQtESFJsvCJoKyvapDg//dEkh36cl1gn3xCXqomGMpD9UcJCtfSvCuBrSlZrkUxBK8="
  distributions: sdist
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
    python: 3.6

after_success:
  - codecov
